apiVersion: v1
kind: Service
metadata:
  name: travel-photos-app
  labels:
    app: travel-photos-app
spec:
  selector:
    app: travel-photos-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP

